import Head from "next/head";
import { useSession, signIn, signOut } from "next-auth/react"
import Feature from "@/components/HomePage/Feature";
import Banner from "@/components/HomePage/Banner";
import Products from "@/components/HomePage/Products";
import NewArrival from "@/components/HomePage/NewArrival";
import Offers from "@/components/HomePage/Offers";

export default function Home() {
  const { data: session } = useSession({ keepAlive: true })
  console.log(session);
  return (

    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner />
      <Feature />
      <Products />
      <NewArrival />
      <Offers />

    </>
  );
}
